# Generated by Django 4.0.4 on 2022-06-02 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_alter_post_author_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_liked',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
