# Generated by Django 4.0.4 on 2022-06-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_post_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(max_length=200000),
        ),
    ]
